"""
Django settings for barbershop project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'core',
    'corsheaders',
    'modeltranslation',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'barbershop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'barbershop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
]

TIME_ZONE = 'Europe/Moscow'  # Укажите вашу временную зону

USE_I18N = True
USE_L10N = True  
USE_TZ = True

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core/static',  # Путь к статике в приложении core
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True  # Разрешить все домены (для теста)

JAZZMIN_SETTINGS = {
    # Название, отображаемое в админке
    "site_title": "Barbershop Admin",

    # Название в интерфейсе (внизу сайдбара)
    "site_header": "Barbershop",

    # Название в табе браузера
    "site_brand": "Barbershop CMS",

    # Логотип (путь к изображению в STATIC или MEDIA)
    # "site_logo": "path/to/logo.png",

    # Иконка для сайта (favicon)
    # "site_icon": "path/to/icon.png",

    # CSS класс для логотипа
    "site_logo_classes": "img-circle",

    # Порядок пунктов меню
    "order_with_respect_to": ["core", "auth", "services", "barbers", "reviews"],

    # Автоматическое скрытие неиспользуемых моделей
    "hide_models": [],

    # Скрыть модель в админке
    # "hide_models": ["app_name.ModelName"],

    # Стиль навигационного меню
    "navigation_expanded": True,

    # Отображение формы поиска в меню
    "show_sidebar": True,

    # Цветовая тема (dark/light/auto)
    "ui_tweaks": {
        "theme": "cosmo",
    },

    # Отображение информации о версии Django в футере
    "show_version": True,
}


# Mistral AI
MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")

# Пороги для модерации
MISTRAL_MODERATIONS_GRADES = {
    "hate_and_discrimination": 0.5,
    "sexual": 0.5,
    "violence_and_threats": 0.5,
    "dangerous_and_criminal_content": 0.5,
    "selfharm": 0.5,
    "health": 0.3,
    "financial": 0.3,
    "law": 0.3,
    "pii": 0.3,
}