# Generated by Django 5.2.1 on 2025-07-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_master_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
    ]
